song_list = {
    1: "UnwelcomeSchool-Mitsukiyo.ogg",
    2: "あの夢をなぞって-YOASOBI.ogg",
    3: "青のすみか-キタニタツヤ.ogg",
    4: "天ノ弱-164.ogg",
    5: "再生-ピコン.ogg",
    6: "怪物-YOASOBI.ogg",
    7: "紅蓮華-Lisa.ogg",
    8: "ベテルギウス-優里.ogg",
    9: "証-flumpool.ogg",
    10: "SPECIALZ-King Gnu.ogg",
    11: "打上花火-DAOKO x 米津玄師.ogg",
    12: "炎-Lisa.ogg",
    13: "Subtitle-Official髭男dism.ogg",
    14: "ロミオとシンデレラ-doriko.ogg",
    15: "獨りんぼエンヴィー-koyori.ogg",
    16: "アスノヨゾラ哨戒班-Orangestar.ogg",
    17: "地球最後の告白を-kemu.ogg",
    18: "TATTOO-Official髭男dism.ogg",
    19: "ツキミソウ-Novelbright.ogg",
    20: "I hate me-Lilyu.ogg",
    21: "不為誰而作的歌-林俊傑.ogg",
    22: "我還是愛著你-MP魔幻力量.ogg",
    23: "傷心的人別聽慢歌-五月天.ogg",
    24: "初音ミクの消失-cosMo@暴走P.ogg",
    25: "HERO-Ayase.ogg",
    26: "君に届け-flumpool.ogg",
    27: "勇者-YOASOBI.ogg",
    28: "粛聖!!ロリ神レクイエム☆-しぐれうい.ogg",
    29: "Happy Halloween-Junky.ogg",
    30: "ノンブレス・オブリージュ.ogg",
    31: "spiral-LONGMAN.ogg",
    32: "宿命-Official髭男dism.ogg",
    33: "私奔到月球-五月天.ogg",
    34: "天外來物-薛之謙.ogg",
    35: "我期待的不是雪-張妙格.ogg",
    36: "說愛你-蔡依林.ogg",
    37: "那些年-胡夏.ogg",
    38: "雪の音-Novelbright.ogg",
    39: "クリスマスイブ-優里.ogg",
    40: "Heart beat-YOASOBI.ogg",
    41: "天ノ弱-akie秋绘.ogg",
    42: "酔いどれ知らず-Kanaria.ogg",
    43: "ただ声ーつ-ロクデナシ.ogg",
    44: "Bling-Bang-BangBorn-CreepyNuts.ogg",
    45: "Dec.-kanaria.ogg",
    46: "心做し-蝶々P.ogg",
    47: "Good night ojosama-ASMRZ.ogg",
    48: "守りたいもの-大原ゆい子.ogg",
    49: "相思相愛-aiko.ogg",
    50: "XY&Z-サトシ.ogg",
    51: "aLIEz-澤野弘之.ogg",
    52: "ファタール-GEMN.ogg",
    53: "ANIMA-ReoNa.ogg",
    54: "うい麦畑でつかまえて-しぐれうい.ogg",
    55: "舞台に立って-YOASOBI.ogg",
    56: "一番輝く星-上坂すみれ.ogg",
    57: "Tell your world-kz.ogg",
    58: "がらくた-米津玄師.ogg",
    59: "柯南主題曲-大野克夫.ogg",
    60: "Don’t Fight The Music-黑魔.ogg",
    61: "only my railgun-fripSide.ogg",
    63: "六兆年と一夜物語-kemu.ogg",
    64: "Azalea-米津玄師.ogg",
    65: "アイビー-Novelbright.ogg",
    66: "50%-Official髭男dism.ogg",
    67: "東京テディベア-Neru.ogg",
    68: "暮色迴響-吉星出租.ogg",
    69: "童話-光良.ogg",
    70: "步步-五月天.ogg",
    71: "我們青春-李玉璽.ogg",
    72: "任性-五月天.ogg",
    73: "APT.-ROSÉ & Bruno Mars.ogg",
    74: "snooze-wotaku.ogg",
    75: "ゴーストルール-DECO_27.ogg",
    76: "余花にみとれて-keeno.ogg",
    77: "YOASOBI合輯.ogg"
}

fortune = [
            '上籤', '上上籤', '上中籤', '上平籤', '上下籤', '大吉籤', '上吉籤', '中吉籤', '下吉籤', '中籤',
            '中上籤', '中平籤', '中中籤', '中下籤', '下籤', '下上籤', '下中籤', '下下籤', '下兇籤', '不吉籤'
]

rewards = {
            '上籤': 400,
            '上上籤': 200,
            '上中籤': 190,
            '上平籤': 180,
            '上下籤': 170,
            '大吉籤': 160,
            '上吉籤': 150,
            '中吉籤': 140,
            '下吉籤': 130,
            '中籤': 120,
            '中上籤': 110,
            '中平籤': 100,
            '中中籤': 90,
            '中下籤': 80,
            '下籤': 70,
            '下上籤': 60,
            '下中籤': 50,
            '下下籤': 40,
            '下兇籤': 30,
            '不吉籤': 20
}

enemies = {
    "外勁一層武者": {"health": 750, "attack": 140, "defense": 46},
    "外勁六層武者": {"health": 1025, "attack": 190, "defense": 61},
    "外勁大圓滿武者": {"health": 1300, "attack": 240, "defense": 76},
    "內勁一層武者": {"health": 1355, "attack": 250, "defense": 79},
    "內勁六層武者": {"health": 1630, "attack": 300, "defense": 91},
}

items = {
    "生命藥水": {"type": "heal", "value": 50, "use_restriction": "both"},  
    "力量藥水": {"type": "buff", "attack": 10, "use_restriction": "combat"},  
    "防禦藥水": {"type": "buff", "defense": 5, "use_restriction": "combat"},  
    "修為": {"type": "gain_cultivation", "value": 100, "use_restriction": "non_combat"},  
    "精華": {"type": "gain_quench", "value": 100, "use_restriction": "non_combat"}  
}

item_prices = {
    "生命藥水": 10,  
    "力量藥水": 20,  
    "防禦藥水": 15,  
    "修為": 100,
    "精華": 250,
}
